export default {
  model: 'test',
  rows: [],
  filter: '',
  errors: [],
  all: [],
  selected: [],
  query: "",
  detailData: {},
  formDialog: false,
  formData: {},
  pagination: {
    sortBy: 'id',
    descending: false,
    page: 1,
    rowsPerPage: 25,
    rowsNumber: 10
  },
  totalNumber: 0,
  filters: {},
  loading: false,
  submitLoading: false,
  exportRows: 0,
  exportName: "",
  modelData: {},
}
